# Many thanks to 
# https://www.meziantou.net/executing-github-actions-jobs-or-steps-only-when-specific-files-change.htm
# for providing the base that this uses

name: Release to PyPI
on:
  push:
    branches:
      - 'main'

jobs:
  conditional_job_check_files:
    runs-on: 'ubuntu-latest'
    # Declare outputs for next jobs
    outputs:
      version_changed: ${{ steps.check_file_changed.outputs.version_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        git diff HEAD^ HEAD | grep -q "+version ="
        
        # shellcheck disable=SC2181
        if [ $? -eq 0 ]
        then
          GOTIME="True"
        else
          GOTIME="False"
        fi
        
        # Set the output named "version_changed"
        echo "version_changed=$GOTIME" >> $GITHUB_OUTPUT

  # Run the job only with "version_changed" equals "True"
  conditional_job:
    runs-on: 'ubuntu-latest'
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.version_changed == 'True'
    steps:
    - name: Push to PyPI
      run: echo "This is where we'll put the pypi deploy step"