name: "Validate Catalog Info"

on:
  push:
    paths:
      - '.spoton/**'
  pull_request:
    paths:
      - '.spoton/**'

jobs:
  validate-catalog-info:
    runs-on: [self-hosted, corp, medium, eks-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: spotoninc/github-action-validate-catalog-info@main